// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  LAST_FM_TOKEN?: string;
  MUSIC_WIDGET_PROVIDER?: "apple-music" | "lastfm";
  APPLE_MUSIC_USER_TOKEN?: string;
  APPLE_MUSIC_PRIVATE_KEY?: string;
  APPLE_MUSIC_KEY_ID?: string;
  APPLE_MUSIC_TEAM_ID?: string;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface ExportedHandler<Env = unknown> {
  fetch?(request: Request, env: Env, ctx: ExecutionContext): Response | Promise<Response>;
}
