"use client";

import { AudioPlayer } from "@/components/AudioPlayer";

export function ListenPanel({ audioUrl }: { audioUrl: string }) {
  return (
    <div className="rounded-lg border bg-background/50 px-4 pt-3 space-y-2.5">
      <AudioPlayer src={audioUrl} />

      <p className="text-[10px] text-muted-foreground/70">
        Note: This audio is generated by a text-to-speech model and may not be 100% accurate.
      </p>
    </div>
  );
}
