name = "website-blog-api"
compatibility_date = "2024-05-01"

[dev]
port = 8786

routes = [
	{ pattern = "blog.s3rve.co.uk", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'blog'
preview_bucket_name = 'blog'

[[queues.consumers]]
queue = "blog-update"
max_batch_size = 100
max_batch_timeout = 5

[[d1_databases]]
binding = "DB"
database_name = "personal-web"
database_id = "cabaa840-522a-42e0-86f4-6309cfdacc79"
