name = "nicholasgriffin-emails"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat" ]

routes = [
  { pattern = "email.nickgriffin.uk", custom_domain = true }
]

[dev]
port = 8786

[[send_email]]
name = "EMAIL"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "emails"
preview_bucket_name = "emails"
